services:
  # kafka1:
  #   image: apache/kafka:4.2.0
  #   container_name: kafka1
  #   ports:
  #     - "9094:9094"
  #   environment:
  #     CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
  #     KAFKA_NODE_ID: 1
  #     KAFKA_PROCESS_ROLES: broker,controller
  #     KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:29093
  #     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,EXTERNAL://${PUBLIC_IP:-localhost}:9094
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  #     KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:29093,2@kafka2:29093,3@kafka3:29093
  #     KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
  #   volumes:
  #     - kafka1-data:/tmp/kraft-combined-logs
  #   networks:
  #     - kafka-net

  # kafka2:
  #   image: apache/kafka:4.2.0
  #   container_name: kafka2
  #   ports:
  #     - "9095:9095"
  #   environment:
  #     CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
  #     KAFKA_NODE_ID: 2
  #     KAFKA_PROCESS_ROLES: broker,controller
  #     KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9095,CONTROLLER://0.0.0.0:29093
  #     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9092,EXTERNAL://${PUBLIC_IP:-localhost}:9095
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  #     KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:29093,2@kafka2:29093,3@kafka3:29093
  #     KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
  #   volumes:
  #     - kafka2-data:/tmp/kraft-combined-logs
  #   networks:
  #     - kafka-net

  # kafka3:
  #   image: apache/kafka:4.2.0
  #   container_name: kafka3
  #   ports:
  #     - "9096:9096"
  #   environment:
  #     CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
  #     KAFKA_NODE_ID: 3
  #     KAFKA_PROCESS_ROLES: broker,controller
  #     KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9096,CONTROLLER://0.0.0.0:29093
  #     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:9092,EXTERNAL://${PUBLIC_IP:-localhost}:9096
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  #     KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:29093,2@kafka2:29093,3@kafka3:29093
  #     KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
  #   volumes:
  #     - kafka3-data:/tmp/kraft-combined-logs
  #   networks:
  #     - kafka-net

  # kafka-bridge:
  #   image: quay.io/strimzi/kafka-bridge:1.0.0
  #   container_name: kafka-bridge
  #   command: /opt/strimzi/bin/kafka_bridge_run.sh --config-file=/opt/strimzi/config/application.properties
  #   expose:
  #     - "8080"
  #   volumes:
  #     - ./kafka-bridge/application.properties:/opt/strimzi/config/application.properties
  #   depends_on:
  #     - kafka1
  #     - kafka2
  #     - kafka3
  #   networks:
  #     - kafka-net

  # nginx-proxy:
  #   image: nginx:alpine
  #   container_name: nginx-proxy
  #   ports:
  #     - "8443:8443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - kafka-bridge
  #   networks:
  #     - kafka-net
  # docker run -d --name timescaledb -p 5432:5432  -v </a/local/data/folder>:/pgdata -e PGDATA=/pgdata -e POSTGRES_PASSWORD=password timescale/timescaledb-ha:pg18
  timescaledb:
    image: timescale/timescaledb-ha:pg18
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      PGDATA: /pgdata
      POSTGRES_PASSWORD: password
      POSTGRES_DB: activitydb
    volumes:
      - timescaledb-data:/pgdata
    networks:
      - kafka-net

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: [ "--js", "-m", "8222", "-a", "0.0.0.0" ]
    networks:
      - kafka-net

volumes:
  kafka1-data:
  kafka2-data:
  kafka3-data:
  timescaledb-data:

networks:
  kafka-net:
    driver: bridge
