services:
  # nginx-proxy:
  #   image: docker.io/nginx:alpine
  #   container_name: nginx-proxy
  #   ports:
  #     - "8443:8443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/ssl:/etc/nginx/ssl:ro
  #   networks:
  #     - vidur-net

  # Docker run : docker run -d --name timescaledb -p 5432:5432  -v </a/local/data/folder>:/pgdata -e PGDATA=/pgdata -e POSTGRES_PASSWORD=password timescale/timescaledb-ha:pg16
  # Enable pgvector extension: "CREATE EXTENSION IF NOT EXISTS vector;"
  # timescaledb:
  #   # Switched to the -ha image to ensure pgvector is available
  #   image: timescale/timescaledb-ha:pg18
  #   container_name: timescaledb
  #   userns_mode: keep-id
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: contexdb
  #     POSTGRES_USER: postgres
  #     PGDATA: /var/lib/postgresql/data/pgdata
  #   volumes:
  #     - /home/bikash/Data/vidur-data/philosophy/ai-timescale-pgvector-data:/var/lib/postgresql/data/pgdata
  #   networks:
  #     - vidur-net
  # nats:
  #   image: docker.io/nats:latest
  #   container_name: nats
  #   ports:
  #     - "4222:4222"
  #     - "8222:8222"
  #   command: [ "--js", "-m", "8222", "-a", "0.0.0.0" ]
  #   volumes:
  #     - natsio-data:/data
  #   networks:
  #     - vidur-net
  milvus:
    image: docker.io/milvusdb/milvus:v2.5.27
    container_name: milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_USE_EMBED: "true"
      ETCD_DATA_DIR: "/var/lib/milvus/etcd"
      ETCD_CONFIG_PATH: "/milvus/configs/embedEtcd.yaml"
      COMMON_STORAGETYPE: "local"
      DEPLOY_MODE: "STANDALONE"
    command: milvus run standalone
    volumes:
      - $HOME/Data/vidur-data/ai-milvus-data:/var/lib/milvus
      - ./embedEtcd.yaml:/milvus/configs/embedEtcd.yaml
      - ./user.yaml:/milvus/configs/user.yaml

  # attu:
  #   image: zilliz/attu:v2.3.5
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - MILVUS_ADDRESS=milvus:19530
  #   volumes:
  #     - attu-data:/data
  #   depends_on:
  #     - milvus

volumes:
  milvus-data:
  attu-data:

networks:
  vidur-net:
    driver: bridge
